name: Secured tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
        CYPRESS_user_password: ${{ secrets.USER_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run  all Cypress tests 
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set Cypress environment variables
        run: echo "CYPRESS_USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> $GITHUB_ENV  

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.1.0
        with:
         install: false 
         command: npx cypress run --env grepTags=github_secret,grepOmitFiltered=true,grepFilterSpecs=true

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: E2E Test Execution Report
           path: cypress/reports/html   