name: Feature tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests 
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install environment
        run: rm -rf node_modules package-lock.json    
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.1.0
        with:
          install: false
          command: npx cypress run --env grepTags=new_feature,grepOmitFiltered=true,grepFilterSpecs=true

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: New Feature Test Execution Report
           path: cypress/reports/html   

      - name: Prepare Workflow Specific Report 
        if: always()
        run: |
               mkdir -p public/feature
               cp -r cypress/reports/html/index.html public/feature/index.html
               cp -r cypress/reports/* public/feature/
               touch public/.nojekyll
         # publishes report at https://chandreyee729.github.io/cpress_e2e_opencart/feature/     

      - name: Deploy Data Report to GitHub Pages
        if: always()  
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
              