name: Smoke tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run  all Cypress tests 
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: 
          npm install --legacy-peer-deps

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.1.0
        with:
         install: false 
         command: npx cypress run --env grepTags=smoke,grepOmitFiltered=true,grepFilterSpecs=true

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: Smoke Test Execution Report
           path: cypress/reports/html   

      - name: Prepare Workflow Specific Report 
        run: |
            mkdir -p public/smoke
            cp -r reports/* public/
            cp public/index.html public/smoke/index.html
            touch public/.nojekyll

        
      - name: Deploy Data Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: smoke
            